version: "3.3"
services:
  my-web-app-db:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  my-web-app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - my-web-app-db
